START /* 0 */ TRANSACTION;

INSERT /* 1 */ INTO `tomes` ( `id`,`name`,`source`,`source_type`,`source_format`,`readable`,`writeable`,`user_id`,`last_updated`,`created`,`modified` )
VALUES ( 2,'English idioms','', 'local', 'json', 2, 0, 0, NOW(), NOW(), NOW() );

INSERT /* 2 */ INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"A STORM IN A TEACUP","ASTORMINATEACUP",NOW(),NOW());
INSERT /* 3 */ INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ADD FUEL TO THE FIRE","ADDFUELTOTHEFIRE",NOW(),NOW());
INSERT /* 4 */ INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ALL EARS","ALLEARS",NOW(),NOW());
INSERT /* 5 */ INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ALL IN THE SAME BOAT","ALLINTHESAMEBOAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ALL SET","ALLSET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"AN ARM AND A LEG","ANARMANDALEG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"APPLE OF ONE'S EYE","APPLEOFONSEYE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"AS RIGHT AS RAIN","ASRIGHTASRAIN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"AT THE DROP OF A HAT","ATTHEDROPOFAHAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"AT THE ELEVENTH HOUR","ATTHEELEVENTHHOUR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BACK IN THE SADDLE","BACKINTHESADDLE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BACK TO SQUARE ONE","BACKTOSQUAREONE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BACK TO THE DRAWING BOARD","BACKTOTTHEDRAWINGBOARD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BALLPARK FIGURE","BALLPARKFIGURE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BARK UP THE WRONG TREE","BARKUPTHEWRONGTREE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BARKING MAD","BARKINGMAD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BEAT ABOUT THE BUSH","BEATABOUTTHEBUSH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BEAT THE CLOCK","BEATTHECLOCK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BEND OVER BACKWARDS","BENDOVERBACKWARDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BETTER LATE THAN NEVER","BETTERLATETHANNEVER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BITE OFF MORE THAN ONE CAN CHEW","BITEOFFMORETHANONECANCHEW",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BITE THE BULLET","BITETHEBULLET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BLACK SHEEP","BLACKSHEEP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BLOW HOT AND COLD","BLOWHOTANDCOLD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BLOW ONE'S OWN TRUMPET","BLOWONESOWNTRUMPET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BONE TO PICK","BONETOPICK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BORN WITH A SILVER SPOON","BORNWITHASILVERSPOON",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BREAK THE BANK","BREAKTHEBANK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BREAK THE ICE","BREAKTHEICE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BRING DOWN THE HOUSE","BRINGDOWNTHEHOUSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BRING HOME THE BACON","BRINGHOMETHEBACON",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BROWN AS A BERRY","BROWNASABERRY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BULL IN A CHINA SHOP","BULLINACHINASHOP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BURN THE CANDLE AT BOTH ENDS","BURNTHECANDLEATBOTHENDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BURN THE MIDNIGHT OIL","BURNTHEMIDNIGHTOIL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BURNING THE MIDNIGHT OIL","BURNINGTHEMIDNIGHTOIL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BUTTER SOMEONE UP","BUTTERSOMEONEUP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BY AND LARGE","BYANDLARGE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"BY THE SKIN OF ONE'S TEETH","BYTHESKINOFDONESSTETH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CALL IT A DAY","CALLITADAY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CAST IN STONE","CASTINSTONE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CAT NAP","CATNAP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CHANGE OF HEART","CHANGEOFHEART",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CHIP ON ONE'S SHOULDER","CHIPONONESSHOULDER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"COLD SHOULDER","COLDSHOULDER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"COME RAIN OR SHINE","COMERAINORSHINE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"COOK THE BOOKS","COOKTHEBOOKS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"COOL AS A CUCUMBER","COOLASACUCUMBER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"COST AN ARM AND A LEG","COSTANARMANDALEG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CROSS THE LINE","CROSSTHELINE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CRY OVER SPILT MILK","CRYOVERSPILTMILK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CURIOSITY KILLED THE CAT","CURIOSITYKILLEDTHECAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CUT CORNERS","CUTCORNERS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"CUT TO THE CHASE","CUTTOTHECHASE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DARK HORSE","DARKHORSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DAYDREAM","DAYDREAM",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DEVIL'S ADVOCATE","DEVILSADVOCATE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DIME A DOZEN","DIMEADOZEN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DOG'S BREAKFAST","DOGSBREAKFAST",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DOWN TO EARTH","DOWNTOEARTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"DROP A CLANGER","DROPACLANGER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"EAT HUMBLE PIE","EATHUMBLEPIE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"EAT ONE'S WORDS","EATONESWORDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ELBOW GREASE","ELBOWGREASE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ELEPHANT IN THE ROOM","ELEPHANTINTHEROOM",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"EVERY CLOUD HAS A SILVER LINING","EVERYCLOUDHASASILVERLINING",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"EYE FOR AN EYE","EYEFORANEYE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FACE THE MUSIC","FACETHEMUSIC",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FALL FLAT","FALLFLAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FALL FROM GRACE","FALLFROMGRACE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FALL ON DEAF EARS","FALLONDEAFEARS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FEATHER IN ONE'S CAP","FEATHERINONESCAP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FIFTH WHEEL","FIFTHWHEEL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FINE TOOTH COMB","FINETOOTHCOMB",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FINGER IN EVERY PIE","FINGERINEVERYPIE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FISH OUT OF WATER","FISHOUTOFWATER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FLY OFF THE HANDLE","FLYOFFTHEHANDLE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FOOD FOR THOUGHT","FOODFORTHOUGHT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FOOT IN THE DOOR","FOOTINTHEDOOR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FOR CRYING OUT LOUD","FORCRYINGOUTLOUD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FREE REIN","FREEREIN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"FULL OF BEANS","FULLOFBEANS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GAME OF TWO HALVES","GAMEOFTWOHALVES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GET COLD FEET","GETCOLDFEET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GET OUT OF HAND","GETOUTOFHAND",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GET WIND OF","GETWINDOF",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GIVE ONE'S RIGHT ARM","GIVEONESRIGHTARM",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GO AGAINST THE GRAIN","GOAGAINSTTHEGRAIN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GO DOWN IN FLAMES","GODOWNINFLAMES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GO THE EXTRA MILE","GOTHEEXTRAMILE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GOLDEN HANDSHAKE","GOLDENHANDSHAKE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GRASP THE NETTLE","GRASPTHENETTLE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"GREEN-EYED MONSTER","GREENEYEDMONSTER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAIR OF THE DOG","HAIROFTHEDOG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAND TO MOUTH","HANDTOMOUTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HANDS DOWN","HANDSDOWN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAVE A BLAST","HAVEABLAST",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAVE A BONE TO PICK","HAVEABONETOPICK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAVE A CHIP ON ONE'S SHOULDER","HAVEACHIPONONESSHOULDER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAVE EYES IN THE BACK OF ONE'S HEAD","HAVEEYESINTHEBACKOFONESHEAD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HAVE THE UPPER HAND","HAVETHEUPPERHAND",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HEAD IN THE CLOUDS","HEADINTHECLOUDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HEADS WILL ROLL","HEADSWILLROLL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HEAR IT ON THE GRAPEVINE","HEARITONTHEGRAPEVINE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HIT ROCK BOTTOM","HITROCKBOTTOM",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HIT THE HAY","HITTHEHAY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HIT THE NAIL ON THE HEAD","HITTHENAILONTHEHEAD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HIT THE SACK","HITTHESACK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HOLD ONE'S HORSES","HOLDONESHORSES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HOLD THE FORT","HOLDTHEFORT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"HOT UNDER THE COLLAR","HOTUNDERTHECOLLAR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IF THE SHOE FITS","IFTHESHOEFITS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN A NUTSHELL","INANUTSHELL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN BLACK AND WHITE","INBLACKANDWHITE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN HOT WATER","INHOTWATER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN ONE'S ELEMENT","INONSELEMENT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN STITCHES","INSTITCHES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN THE NICK OF TIME","INTHENICKOFTIME",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IN THE SAME BOAT","INTHESAMEBOAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"IT TAKES TWO TO TANGO","ITTAKESTWOTOTANGO",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"JUMP ON THE BANDWAGON","JUMPONTHEBANDWAGON",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"JUMP THE GUN","JUMPTHEGUN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"JUMP THE QUEUE","JUMPTHEQUEUE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KEEP ONE'S CHIN UP","KEEPONESCHINUP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KEEP ONE'S NOSE CLEAN","KEEPONESNOSECLEAN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KEEP THE WOLF FROM THE DOOR","KEEPTHEWOLFFROMTHEDOOR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KICK THE BUCKET","KICKTHEBUCKET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KICK UP A FUSS","KICKUPAFUSS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KILL TWO BIRDS WITH ONE STONE","KILLTWOBIRDSWITHONESTONE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KNOCK ON WOOD","KNOCKONWOOD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KNOW THE ROPES","KNOWTHEROPES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"KNUCKLE DOWN","KNUCKLEDOWN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LABOUR OF LOVE","LABOUROFLOVE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LAND ON ONE'S FEET","LANDONONESFEET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LAP OF LUXURY","LAPOFLUXURY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LAST BUT NOT LEAST","LASTBUTNOTLEAST",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LAUGH ONE'S HEAD OFF","LAUGHONESHEADOFF",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LAY DOWN THE LAW","LAYDOWNTHELAW",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LEAD ASTRAY","LEADASTRAY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LEAD ONE UP THE GARDEN PATH","LEADONEUPTHEGARDENPATH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LEAVE NO STONE UNTURNED","LEAVENOSTONEUNTURNED",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LEFT IN THE LURCH","LEFTINTHELURCH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LEND AN EAR","LENDANEAR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LET BYGONES BE BYGONES","LETBYGONESBEBYGONES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LET SLEEPING DOGS LIE","LETSLEEPINGDOGSLIE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LET THE CAT OUT OF THE BAG","LETTHECATOUTOFTHEBAG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LICK ONE'S WOUNDS","LICKONESWOUNDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LIGHT AT THE END OF THE TUNNEL","LIGHTATTHEENDOFTHETUNNEL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LIKE FATHER LIKE SON","LIKEFATHERLIKESON",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LION'S SHARE","LIONSSHARE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LIVE AND LEARN","LIVEANDLEARN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LIVE WIRE","LIVEWIRE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOCK STOCK AND BARREL","LOCKSTOCKANDBARREL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOOK A GIFT HORSE IN THE MOUTH","LOOKAGIFTHORSEINTHEMOUTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOOK BEFORE YOU LEAP","LOOKBEFOREYOULEAP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOSE ONE'S HEAD","LOSEONESHEAD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOSE ONE'S TEMPER","LOSEONESTEMPER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOSE TRACK OF TIME","LOSETRACKOFTIME",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOVE AT FIRST SIGHT","LOVEATFIRSTSIGHT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LOW-HANGING FRUIT","LOWHANGINGFRUIT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"LUCK OF THE DRAW","LUCKOFTHEDRAW",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE A BEELINE FOR","MAKEABEELINEFOR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE A CLEAN BREAST OF IT","MAKEACLEANBREASTOFIT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE A MOUNTAIN OUT OF A MOLEHILL","MAKEAMOUNTAINOUTOFAMOLEHILL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE ENDS MEET","MAKEENDSMEET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE ONE'S MARK","MAKEONESMARK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE ONE'S PRESENCE FELT","MAKEONESPRESENCEFELT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAKE THE GRADE","MAKETHEGRADE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MAN OF THE WORLD","MANOFTHEWORLD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MARK MY WORDS","MARKMYWORDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MEET ONE'S MATCH","MEETONESMATCH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MEND FENCES","MENDFENCES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"METHOD IN ONE'S MADNESS","METHODINONESMADNESS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MIND ONE'S OWN BUSINESS","MINDONESOWNBUSINESS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MISS THE BOAT","MISSTHEBOAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MONKEY BUSINESS","MONKEYBUSINESS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MOVE HEAVEN AND EARTH","MOVEHEAVENANDEARTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"MUM'S THE WORD","MUMSTHEWORD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NAIL ONE'S COLOURS TO THE MAST","NAILONESCOLOURSTOTHEMAST",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NAKED TRUTH","NAKEDTRUTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NAME AND SHAME","NAMEANDSHAME",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NECK OF THE WOODS","NECKOFTHEWOODS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NEEDLE IN A HAYSTACK","NEEDLEINAHAYSTACK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NEITHER HERE NOR THERE","NEITHERHERENORTHERE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NEVER SAY DIE","NEVERSAYDIE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NEW LEASE OF LIFE","NEWLEASEOFLIFE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NIP IN THE BUD","NIPINTHEBUD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NO PAIN NO GAIN","NOPAINNOGAIN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NOT ONE'S CUP OF TEA","NOTONESCUPOFTEA",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NOT ROCKET SCIENCE","NOTROCKETSCIENCE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NOT WORTH A FIG","NOTWORTHAFIG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"NOTHING TO WRITE HOME ABOUT","NOTHINGTOWRITEHOMEABOUT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OFF COLOUR","OFFCOLOUR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OFF THE CUFF","OFFTHECUFF",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OFF THE HOOK","OFFTHEHOOK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OFF THE RECORD","OFFTHERECORD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OLD HAT","OLDHAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON A ROLL","ONAROLL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON CLOUD NINE","ONCLOUDNINE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON ONE'S LAST LEGS","ONONESLASTLEGS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON THE BALL","ONTHEBALL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON THE FENCE","ONTHEFENCE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON THE HOUSE","ONTHEHOUSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON THE ROCKS","ONTHEROCKS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON THE TIP OF ONE'S TONGUE","ONTHETIPOFONESTONGUE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ON THIN ICE","ONTHINICE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ONCE IN A BLUE MOON","ONCEINABLUEMOON",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ONE FOOT IN THE GRAVE","ONEFOOTINTHEGRAVE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ONE IN A MILLION","ONEINAMILLION",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ONE STEP AT A TIME","ONESTEPATATIME",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OPEN A CAN OF WORMS","OPENACANOFWORMS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OPEN AND SHUT CASE","OPENANDSHUTCASE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OPEN SECRET","OPENSECRET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OUT AND ABOUT","OUTANDABOUT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OUT OF ONE'S DEPTH","OUTOFONESDEPTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OUT OF SIGHT OUT OF MIND","OUTOFSIGHTOUTOFMIND",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OUT OF THE FRYING PAN INTO THE FIRE","OUTOFTHEFRYINGPANINTOTHEFIRE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"OVER THE MOON","OVERTHEMOON",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PAIN IN THE NECK","PAININTHENECK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PAINT THE TOWN RED","PAINTTHETOWNRED",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PAPER OVER THE CRACKS","PAPEROVERTHECRACKS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PART AND PARCEL","PARTANDPARCEL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PASS THE BUCK","PASSTHEBUCK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PAY THROUGH THE NOSE","PAYTHROUGHTHENOSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PEAR SHAPED","PEARSHAPED",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PIECE OF CAKE","PIECEOFCAKE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PLAY IT BY EAR","PLAYITBYEAR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PULL ONE'S LEG","PULLONESLEG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"PULL STRINGS","PULLSTRINGS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RACK ONE'S BRAINS","RACKONESBRAINS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RAINING CATS AND DOGS","RAININGCATSANDDOGS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"READ BETWEEN THE LINES","READBETWEENTHELINES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RED HERRING","REDHERRING",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RED TAPE","REDTAPE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"REST ON ONE'S LAURELS","RESTONONESLAURELS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RING A BELL","RINGABELL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RINGS A BELL","RINGSABELL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RISE AND SHINE","RISEANDSHINE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ROAD TO NOWHERE","ROADTONOWHERE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ROB PETER TO PAY PAUL","ROBPETER TOPAYPAUL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ROME WAS NOT BUILT IN A DAY","ROMEWASNOTBUILTINADAY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RUB SALT IN THE WOUND","RUBSALTINTHEWOUND",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RULE OF THUMB","RULEOFTHUMB",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"RUN OUT OF STEAM","RUNOUTOFSTEAM",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SAFE AND SOUND","SAFEANDSOUND",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SALT OF THE EARTH","SALTOFTHEEARTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SAVED BY THE BELL","SAVEDBYTHEBELL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SCARE THE PANTS OFF","SCARETHEPANTSOFF",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SEE EYE TO EYE","SEEEYETOEYE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SEE THE LIGHT","SEETHELIGHT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SET IN STONE","SETINSTONE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SHOOT ONESELF IN THE FOOT","SHOOTONESELFIN THEFOOT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SHOT IN THE DARK","SHOTINTHEDARK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SHOW ONE'S TRUE COLOURS","SHOWONESTRUECOLOURS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SIT ON THE FENCE","SITONTHEFENCE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SIT TIGHT","SITTIGHT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SKATING ON THIN ICE","SKATINGONTHINICE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SKELETON IN THE CUPBOARD","SKELETONINTHECUPBOARD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SLEEPING DOGS LIE","SLEEPINGDOGSLIE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SMELL A RAT","SMELLARAT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SMOKE AND MIRRORS","SMOKEANDMIRRORS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SOUR GRAPES","SOURGRAPES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SOW WILD OATS","SOWWILDOATS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SPANNER IN THE WORKS","SPANNERINTHEWORKS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SPEAK OF THE DEVIL","SPEAKOFTHEDEVIL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SPILL THE BEANS","SPILLTHEBEANS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SPIN A YARN","SPINAYARN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SPLIT HAIRS","SPLITHAIRS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"SQUARE PEG IN A ROUND HOLE","SQUAREPEGINAROUNDHOLE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STAB IN THE BACK","STABINTHEBACK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STAND ON CEREMONY","STANDONCEREMONY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STEAL ONE'S THUNDER","STEALONESTHUNDER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STICK TO ONE'S GUNS","STICKTOONESGUNS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STONE'S THROW","STONESTHROW",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STORM IN A TEACUP","STORMINATEACUP",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"STRAIGHT FROM THE HORSE'S MOUTH","STRAIGHTFROMTHEHORSESMOUTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TAKE A RAIN CHECK","TAKEARAINCHECK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TAKE IT WITH A PINCH OF SALT","TAKEITWITHAPINCHOFSALT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TAKE THE BISCUIT","TAKETHEBISCUIT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TAKE THE PLUNGE","TAKETHEPLUNGE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TAKE WITH A PINCH OF SALT","TAKEWITHAPINCHOFSALT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THE BEST OF BOTH WORLDS","THEBESTOFBOTHWORLDS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THE ICING ON THE CAKE","THEICINGONTHECAKE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THE LAST STRAW","THELASTSTRAW",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THE SPICE OF LIFE","THESPICEOFLIFE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THE STRAW THAT BROKE THE CAMEL'S BACK","THESTRAWTHATBROKETHECAMELSBACK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THE TIP OF THE ICEBERG","THETIPOFTHEICEBERG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THICK AND THIN","THICKANDTHIN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THICK AS THIEVES","THICKASTHIEVES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THROUGH THICK AND THIN","THROUGHTHICKANDTHIN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THROW IN THE TOWEL","THROWINTHETOWEL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"THROW ONE'S WEIGHT AROUND","THROWONESWEIGHTAROUND",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TIE THE KNOT","TIETHEKNOT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TIGHT-LIPPED","TIGHTLIPPED",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TIME IS MONEY","TIMEISMONEY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TIP OF THE ICEBERG","TIPOFTHEICEBERG",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TO CUT A LONG STORY SHORT","TOCUTALONGSTORYSHORT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TOE THE LINE","TOETHELINE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TONGUE IN CHEEK","TONGUEINCHEEK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TOUCH WOOD","TOUCHWOOD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TURN A BLIND EYE","TURNABLINDEYE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TURN THE TABLES","TURNTHETABLES",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TWIST ONE'S ARM","TWISTONESARM",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"TWO PEAS IN A POD","TWOPEASINAPOD",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"UNDER ONE'S NOSE","UNDERONESNOSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"UNDER THE WEATHER","UNDERTHEWEATHER",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"UP IN ARMS","UPINARMS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"UP IN THE AIR","UPINTHEAIR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"UP TO SCRATCH","UPTOSCRATCH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"UPHILL BATTLE","UPHILLBATTLE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"VARIETY IS THE SPICE OF LIFE","VARIETYISTHESPICEOFLIFE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"VOTE WITH ONE'S FEET","VOTEWITHONESFEET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WAIT FOR THE DUST TO SETTLE","WAITFORTHEDUSTTOSETTLE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WALKING ON AIR","WALKINGONAIR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WATER UNDER THE BRIDGE","WATERUNDERTHEBRIDGE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WEAR ONE'S HEART ON ONE'S SLEEVE","WEARONESHEARTONONESSLEEVE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WET BLANKET","WETBLANKET",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WHEEL AND DEAL","WHEELANDDEAL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WHEN PIGS FLY","WHENPIGSFLY",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WILD GOOSE CHASE","WILDGOOSECHASE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WIN BY A NOSE","WINBYANOSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WIN HANDS DOWN","WINHANDSDOWN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WIPE THE SLATE CLEAN","WIPETHESLATECLEAN",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WITH A FINE TOOTH COMB","WITHAFINETOOTHCOMB",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WOLF IN SHEEP'S CLOTHING","WOLFINSHEEPSCLOTHING",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WORD OF MOUTH","WORDOFMOUTH",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WORTH ONE'S SALT","WORTHONESSALT",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WRITING ON THE WALL","WRITINGONTHEWALL",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"WRONG END OF THE STICK","WRONGENDOFTHESTICK",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"YELLOW-BELLIED","YELLOWBELLIED",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"YOU CAN'T HAVE IT BOTH WAYS","YOUCANTHAVEITBOTHWAYS",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"YOUNG AT HEART","YOUNGATHEART",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ZERO HOUR","ZEROHOUR",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ZIGZAG COURSE","ZIGZAGCOURSE",NOW(),NOW());
INSERT INTO `tome_entries` (`tome_id`, `word`, `bare_letters`, `created`, `modified`) VALUES (2,"ZIP ONE'S LIP","ZIPONESLIP",NOW(),NOW());

CALL PopulateLetterCounts();

COMMIT;